### ISSUE TITLE
venn Function name

### ISSUE THREAD

**Issue by farid-zare** [manhowong/matlab-venn#2]
Hi, 
Thanks for your function.
I suggest to rename it since there is already a venn function as MATLAB built in function. So that it would be easier to add to MATLAB

**Comment by manhowong** [comment]
Hi Farid, thank you for your feedback! Sorry for the delayed response because my plate is a bit full at the moment. MATLAB's official documentation does not have a function named "venn". Perhaps you saw that in another package?
